# Generated by Django 5.2.4 on 2025-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_create_date_post_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, upload_to="media/"),
        ),
    ]
